name: E2E test

on:
  workflow_dispatch:
    inputs:
      cases:
        description: 'specific cases to be excuted. Sample: ["./aad/a.tests.ts", "./bot/b.tests.ts"]. Set empty to run all cases'
        required: false

  schedule:
    - cron: "0 22 * * *"

  pull_request:
    types:
      - opened

jobs:
  setup:
    if: ${{  github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == 'teamsfx-bot/TeamsFx')  }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (dev)
        if: ${{  github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'  }}
        uses: actions/checkout@v3


  execute-case:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout (dev)
        run: |
          echo "execute-cases"
